### ISSUE TITLE
[docs] Recursive flag when first cloning from GitHub

### ISSUE THREAD

**Issue by arpastrana** [BlockResearchGroup/compas_libigl#1]
Perhaps it would be useful to state in the `readme` that if cloning from the terminal, one should be using the `recursive` flag, since the dependencies should be cloned too (e.g. `eigen`).

In my case: `git clone url` did not work, but `git clone --recursive url` did.

`pip install -e .` ran smoothly afterwards.

**Comment by brgcode** [comment]
solved since e935a28
