### ISSUE TITLE
[docs]: Rebuilding when modifying c++ backend

### ISSUE THREAD

**Issue by arpastrana** [BlockResearchGroup/compas_libigl#3]
I think it would be useful to mention in the documentation that, whenever one makes some changes to the base c++ code (e.g. add one more python binding), it has to be recompiled with `cmake` in order to reflect the changes when reimporting in python. 

Of course `pip install -e .` takes care of this when installing the very first time; but whenever I kept making changes, to make it run I had to do:

```
cd build
cmake ../
make
```
This will be particularly of interest to the python user-base which might not be entirely familiar with c++.

**Comment by brgcode** [comment]
solved in b04c575
