### ISSUE TITLE
CGAL dependency problem

### ISSUE THREAD

**Issue by philianeles** [BlockResearchGroup/compas_libigl#4]
Having this error after installation:
![image](https://user-images.githubusercontent.com/11179066/76858895-9a199500-6858-11ea-9e7a-a45f75632f7b.png)

Hint: problem with the build of the boolean functions on windows because of the CGAL dependency.

**Comment by brgcode** [comment]
i am aware of this problem (on windows). if you don't need the boolean operations, you can just leave them out. to do so, edit the following files:

* `modules/CMakeLists.txt`: comment line 6 (`add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/booleans)`)
* `src/compas_libigl/__init__.py`: comment line 5 (`from .booleans import *`)

let me know if that doesn't work...

**Comment by brgcode** [comment]
@KIKI007 this is the problem with the CGAL dependency i mentioned during the last meeting. would you mind having a look?

**Comment by philianeles** [comment]
> i am aware of this problem (on windows). if you don't need the boolean operations, you can just leave them out. to do so, edit the following files:
> 
> * `modules/CMakeLists.txt`: comment line 6 (`add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/booleans)`)
> * `src/compas_libigl/__init__.py`: comment line 5 (`from .booleans import *`)
> 
> let me know if that doesn't work...


I have left out the boolen operations. There is also this problem now:
![image](https://user-images.githubusercontent.com/11179066/77342580-b2921f80-6d30-11ea-95e9-3975a2682137.png)

**Comment by brgcode** [comment]
ha sorry forgot about that one. it does multiple boolean operations at once. should also be left out for the same reason...
