### ISSUE TITLE
error trying to construct mesh from_off or from_ply

### ISSUE THREAD

**Issue by philianeles** [BlockResearchGroup/compas_libigl#5]
I am trying to run `planarize_quads_rhino` example.

when mesh is constructed `from_json` it works:
![image](https://user-images.githubusercontent.com/11179066/77769328-fb551b80-7043-11ea-9820-0315f40363df.png)

However having this error when I try to construct the mesh with `from_off` or `from_ply` methods - any hints how to avoid this?
![image](https://user-images.githubusercontent.com/11179066/77769517-3eaf8a00-7044-11ea-96a1-0fa067fe0221.png)

Thank you!

**Comment by brgcode** [comment]
that sounds more like a problem with the off and ply parsers. will have a look...

**Comment by brgcode** [comment]
i noticed that the `.off` you are trying to planarize is the "bunny". this is a triangle mesh and the planarisation functions only work on quads (triangles are flat per definition...).

i added PLY and OFF writing functions to  `compas` and updated the `planarize_mesh_rhino.py` example to convert the "tubemesh.json" to "tubemesh.off" and use the latter for the planarization. that seems to work for me. coulg you give this a try?

note that the OFF and PLY functions are not released yet so you need COMPAS to be installed from source and update to the latest dev version for this to work...

**Comment by philianeles** [comment]
yes that seems to work!

**Comment by brgcode** [comment]
cool, so i can close this?
