### ISSUE TITLE
error running planarize_mesh_rhino

### ISSUE THREAD

**Issue by philianeles** [BlockResearchGroup/compas_libigl#6]
Also, when trying to run `planarize_mesh_rhino` I have this error:
![image](https://user-images.githubusercontent.com/11179066/77777316-b1723280-704f-11ea-8d06-2e8aef35c01e.png)

Ps. I am starting the server externally...
with:
`from compas.rpc import Proxy  `
`p = Proxy()`

**Comment by brgcode** [comment]
i have updated the functions quite considerably. the "mesh" variant does not exist anymore. could you test if `planarize_rhino.py` works for you?

make sure to stop and start the server to allow it to load the new functionality...

**Comment by philianeles** [comment]
it works!
