### ISSUE TITLE
Question on pybind11 debugging tools 

### ISSUE THREAD

**Issue by ioanna21** [BlockResearchGroup/compas_libigl#8]
Hello,
I was wondering what workflow you are using to debug the C++ modules that are called from python. I tried adding Visual Studio breakpoints, but instead of being able to step into the library C++ functions, it takes me instead to the pybind11.h functions. I wonder if I am missing some step. What do you use to do the debugging?

Thanks,
Ioanna

**Comment by brgcode** [comment]
you could use cmake in debug mode.
in `setup.py` change line 54
```
cfg = 'Debug' if self.debug else 'Release'
```
to
```
cfg = 'Debug'
```
there should be an easy way to trigger this programmatically, but it is unknown to me :)

**Comment by ioanna21** [comment]
Yes, finally it works! Now I can step into all the C++ code from python, this is great!
Many thanks!
